{{- $fullname := include "octobatch.fullname" . -}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
{{- $imageRepo := default $.Values.image.repository ($svc.image.repository | default "") -}}
{{- $imageTag := default $.Values.image.tag ($svc.image.tag | default "") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-{{ $name | lower }}
  labels:
    app.kubernetes.io/name: {{ include "octobatch.name" $ }}
    app.kubernetes.io/component: {{ $name | lower }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
spec:
  replicas: {{ default 1 $svc.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "octobatch.name" $ }}
      app.kubernetes.io/component: {{ $name | lower }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "octobatch.name" $ }}
        app.kubernetes.io/component: {{ $name | lower }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      serviceAccountName: {{ include "octobatch.serviceAccountName" $ }}
      securityContext:
{{ toYaml $.Values.global.podSecurityContext | indent 8 }}
      containers:
        - name: {{ $name | lower }}
          image: "{{ $imageRepo }}:{{ $imageTag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $svc.port | default 8000 }}
              protocol: TCP
          env:
            - name: OCTOBATCH_SERVICE_NAME
              value: {{ $name | lower | quote }}
            - name: OCTOBATCH_ENVIRONMENT
              value: {{ $.Values.global.environment | quote }}
            - name: OCTOBATCH_GITHUB_API_BASE_URL
              value: {{ $.Values.global.github.apiBaseUrl | quote }}
            - name: OCTOBATCH_POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.databaseSecret }}
                  key: POSTGRES_DSN
            - name: OCTOBATCH_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.redisSecret }}
                  key: REDIS_URL
            - name: OCTOBATCH_BLOBSTORE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.blobstoreSecret }}
                  key: BLOBSTORE_ENDPOINT
            - name: OCTOBATCH_BLOBSTORE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.blobstoreSecret }}
                  key: BLOBSTORE_BUCKET
            - name: OCTOBATCH_BLOBSTORE_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.blobstoreSecret }}
                  key: BLOBSTORE_ACCESS_KEY_ID
            - name: OCTOBATCH_BLOBSTORE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.blobstoreSecret }}
                  key: BLOBSTORE_SECRET_ACCESS_KEY
            - name: OCTOBATCH_BLOBSTORE_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.blobstoreSecret }}
                  key: BLOBSTORE_SESSION_TOKEN
            - name: OCTOBATCH_GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.github.appCredentialsSecret }}
                  key: GITHUB_APP_ID
            - name: OCTOBATCH_GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.github.appCredentialsSecret }}
                  key: GITHUB_APP_PRIVATE_KEY
            - name: OCTOBATCH_GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.github.appCredentialsSecret }}
                  key: GITHUB_WEBHOOK_SECRET
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
{{ toYaml $svc.resources | indent 12 }}
          securityContext:
{{ toYaml $.Values.global.containerSecurityContext | indent 12 }}
---
{{- end }}
{{- end }}
