{{- $fullname := include "octobatch.fullname" . -}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $name | lower }}
  labels:
    app.kubernetes.io/name: {{ include "octobatch.name" $ }}
    app.kubernetes.io/component: {{ $name | lower }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "octobatch.name" $ }}
    app.kubernetes.io/component: {{ $name | lower }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    - name: http
      port: {{ $svc.port | default 8000 }}
      targetPort: http
      protocol: TCP
---
{{- end }}
{{- end }}
